// <auto-generated />
using System;
using FUNewsTradingSystem_DataAccessLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUNewsTradingSystem_DataAccessLayer.Migrations
{
    [DbContext(typeof(FUNewsManagementContext))]
    partial class FUNewsManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryDescription = "Technology sector",
                            CategoryName = "Technology",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryDescription = "Healthcare sector",
                            CategoryName = "Healthcare",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryDescription = "Financial sector",
                            CategoryName = "Finance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryDescription = "Energy sector",
                            CategoryName = "Energy",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryDescription = "Digital assets",
                            CategoryName = "Cryptocurrencies",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryDescription = "Goods bought and used by consumers",
                            CategoryName = "Consumer Goods",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.NewsArticle", b =>
                {
                    b.Property<int>("NewsArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsArticleID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NewsStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NewsTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UpdatedByID")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("UpdatedByID");

                    b.ToTable("NewsArticle", (string)null);
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.NewsTag", b =>
                {
                    b.Property<int>("NewsArticleID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("NewsTag", (string)null);
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.SystemAccount", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AccountRole")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountEmail")
                        .IsUnique();

                    b.ToTable("SystemAccount", (string)null);

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            AccountEmail = "staff@FUNewsTradingSystem.org",
                            AccountName = "Test Staff",
                            AccountPassword = "@@abc123@@_HASH_PLACEHOLDER",
                            AccountRole = 1
                        },
                        new
                        {
                            AccountID = 2,
                            AccountEmail = "lecturer@FUNewsTradingSystem.org",
                            AccountName = "Test Lecturer",
                            AccountPassword = "@@abc123@@_HASH_PLACEHOLDER",
                            AccountRole = 2
                        });
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagID");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            Note = "Apple Inc.",
                            TagName = "AAPL"
                        },
                        new
                        {
                            TagID = 2,
                            Note = "NVIDIA Corporation",
                            TagName = "NVDA"
                        },
                        new
                        {
                            TagID = 3,
                            Note = "Microsoft Corporation",
                            TagName = "MSFT"
                        },
                        new
                        {
                            TagID = 4,
                            Note = "Alphabet Inc. (Google)",
                            TagName = "GOOGL"
                        },
                        new
                        {
                            TagID = 5,
                            Note = "Tesla, Inc.",
                            TagName = "TSLA"
                        },
                        new
                        {
                            TagID = 6,
                            Note = "Bitcoin",
                            TagName = "BTC"
                        },
                        new
                        {
                            TagID = 7,
                            Note = "Ethereum",
                            TagName = "ETH"
                        },
                        new
                        {
                            TagID = 8,
                            Note = "Amazon.com, Inc.",
                            TagName = "AMZN"
                        });
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.Category", b =>
                {
                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.NewsArticle", b =>
                {
                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.Category", "Category")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.SystemAccount", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.SystemAccount", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.NewsTag", b =>
                {
                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.NewsArticle", "NewsArticle")
                        .WithMany("NewsTagList")
                        .HasForeignKey("NewsArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FUNewsTradingSystem_DataAccessLayer.Models.Tag", "Tag")
                        .WithMany("NewsTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.NewsArticle", b =>
                {
                    b.Navigation("NewsTagList");
                });

            modelBuilder.Entity("FUNewsTradingSystem_DataAccessLayer.Models.Tag", b =>
                {
                    b.Navigation("NewsTags");
                });
#pragma warning restore 612, 618
        }
    }
}
